name: Build Native Library

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
    
    - name: Build Native Library
      run: |
        echo "NDK_HOME=/opt/hostedtoolcache/ndk/r21e/x64"
        export NDK_PROJECT_PATH=${{ github.workspace }}
        cd ${{ github.workspace }}
        /opt/hostedtoolcache/ndk/r21e/x64/ndk-build
        
    - name: List Build Output
      run: |
        ls -R libs/
        
    - name: Create Artifact Directory
      run: |
        mkdir -p artifacts
        cp -r libs/* artifacts/
        
    - uses: actions/upload-artifact@master
      with:
        name: native-libs
        path: artifacts
