name: Build Native Library

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
        
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
    
    - name: Build Native Library
      run: |
        echo "NDK_HOME=/opt/hostedtoolcache/ndk/r21e/x64"
        export NDK_PROJECT_PATH=${{ github.workspace }}
        cd ${{ github.workspace }}
        /opt/hostedtoolcache/ndk/r21e/x64/ndk-build
        
    - name: Commit and Push
      env:
        PAT: ${{ secrets.PAT }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://${PAT}@github.com/TONY-XHY/SignatureKiller.git
        git add libs/
        git commit -m "Add compiled native libraries [skip ci]"
        git push
