name: Build Native Library

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r21e
    
    - name: Build Native Library
      run: |
        echo "NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}"
        ${{ steps.setup-ndk.outputs.ndk-path }}/ndk-build
